Algoritmo "par_impar"
// Descrição: Fazer um algoritmo que leia um número e imprima se o
// número é par ou ímpar.
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 19/03/2019
Var
  n1 : inteiro


Inicio
   escreva("Digite um numero do tipo inteiro: ")
   leia(n1)
   se n1 % 2 = 0 entao
      escreva(" O numero digitado é PAR")
   senao
      escreva(" O numero digitado é IMPAR")
    fimse

Fimalgoritmo