Algoritmo "valor_decrescente"
// Escreva um algoritmo que leia dois valores inteiros e diferentes,
// e mostreos em ordem decrescente.

Var
 n1,n2,maior:inteiro

Inicio
escreva("Digite o 1º valor: ")
leia(n1)
escreva("Digite o 2º valor: ")
leia(n2)
se n1 > n2 entao
    escreva(" Os valores digitados em ordem decrescente é: ",n1,"e", n2)
senao
    escreva(" Os valores digitados em ordem decrescente é: ",n2,"e", n1)
fimse

Fimalgoritmo