Algoritmo "Tabuada_Para"
// Algoritimo e logica de programação 
// Profª Jaqueline 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/04/2019
Var
// Seção de Declarações das variáveis 
  N, i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc...
escreva("Digite um numero para ver a tabuada: ")
leia(N)
   para i de 0 ate 10 faca
      escreval(N:2, " x ", i:2," = ",i*N:2)
   fimpara


Fimalgoritmo